### ISSUE TITLE
[Bug][External Plugins] External plugins' scripts cannot run as non-root

### ISSUE THREAD

**Issue by JorgeGar** [apache/incubator-devlake#5128]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Devlake cannot be run as non-root. When trying to run DevLake backend as non-root, it tries to load the external plugins by running some scripts (i.e. [azuredevops/run.sh](https://github.com/apache/incubator-devlake/blob/main/backend/python/plugins/azuredevops/run.sh) ) and fails with "Permission denied" message.

```
time="2023-05-08 09:53:17" level=info msg="Loading remote plugins"
time="2023-05-08 09:53:17" level=error msg="./run.sh: 20: poetry: Permission denied"
time="2023-05-08 09:53:17" level=error msg="failed to load plugins
	caused by: Error calling plugin-info
	Wraps: (2) get error when invoking remote function plugin-info
	Wraps: (3) remote error response:
	  | ./run.sh: 20: poetry: Permission denied
	Wraps: (4) exit status 127
	Wraps: (5) exit status 127
	Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *hintdetail.withDetail (5) *exec.ExitError"
panic: Error calling plugin-info
Wraps: (2) get error when invoking remote function plugin-info
Wraps: (3) remote error response:
  | ./run.sh: 20: poetry: Permission denied
Wraps: (4) exit status 127
Wraps: (5) exit status 127
Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *hintdetail.withDetail (5) *exec.ExitError

goroutine 1 [running]:
github.com/apache/incubator-devlake/server/services.Init()
	/app/server/services/init.go:90 +0x225
github.com/apache/incubator-devlake/server/api.CreateApiService()
	/app/server/api/api.go:61 +0x2e
main.main()
	/app/server/main.go:39 +0x7e
```

### What do you expect to happen

DevLake should be able to run as non-root.

### How to reproduce

Deploy Devlake in a kubernetes cluster (minikube) with helm adding these values:

```
lake:
  securityContext:
    fsGroup: 101
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 101
  
  containerSecurityContext: 
    allowPrivilegeEscalation: false
    capabilities:
      drop: 
          - all
```

You can also try to run it with Docker setting a non-root user.

### Anything else

I think it should be easy to fix by changing the ownership of the app folder in the Dockerfile. Maybe you could setup a specific non-root user to run the application.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JorgeGar** [comment]
A small correction here. The `run.sh` runs fine, it's the Python code on the folder that's failing. 
`./run.sh: 20: poetry: Permission denied`

**Comment by JorgeGar** [comment]
Another possible cause is that Poetry is installed by default only on the user. But it can be installed in a different path: https://python-poetry.org/docs/

**Comment by mindlesscloud** [comment]
Hi @JorgeGar , thanks for your report.

@keon94, would you take a look at this issue?

**Comment by JorgeGar** [comment]
> Hi @JorgeGar , thanks for your report.
> 
> @keon94, would you take a look at this issue?

Hi @mindlesscloud, @keon94, I have a few ideas on how to solve it that I hope will help. They won't be the prettiest, but I've been testing and they should work:

-  The easiest would be to create a user and make sure that the user has poetry installed. That would force us to use that user in the security context, but that's already the case for the UI because of Nginx...

-  Another option would be to install Poerty in a different path and modify the code so it uses that full path binary instead of relying on the Path env variable.

I will try and post one of the options in a PR so we can discuss it there.

**Comment by IronCore864** [comment]
One best practice when running a container is to launch the process with a non root user.

Can we create a non-root user in the Docker image, make sure that the user has permission to execute the Python stuff, and run the container as that user?

**Comment by keon94** [comment]
I'll try to look into this sometime this week.

**Comment by awickham10** [comment]
Was anyone able to figure anything out with this? I'm trying to setup a POC of devlake in our environment and our K8s software doesn't support running as root, so I'm stuck.

I tried disabling remote plugins, but whatever I'm doing isn't getting the job done.

Thanks!

**Comment by keon94** [comment]
@awickham10 How are you disabling the remote plugins? With the `DISABLED_REMOTE_PLUGINS=true` env var? If yes, what error do you still get? Because that should completely turn off execution of python/poetry.

**Comment by awickham10** [comment]
> @awickham10 How are you disabling the remote plugins? With the `DISABLED_REMOTE_PLUGINS=true` env var? If yes, what error do you still get? Because that should completely turn off execution of python/poetry.

I finally did disable it by setting the remote plugin path to empty. Of course the Azure DevOps one we want trial is a remote one though.

**Comment by keon94** [comment]
@IronCore864 do you have anytime soon to tackle this? I believe your proposal is the correct solution.

**Comment by IronCore864** [comment]
After discussion, @ZhangNing10 will work on it and she's already got a working version to be tested.

**Comment by ZhangNing10** [comment]
@JorgeGar @IronCore864 @keon94 @matrixji could you kindly help review the pr https://github.com/apache/incubator-devlake/pull/5583

**Comment by keon94** [comment]
The PR has been merged. This feature should be available in v0.18.

**Comment by eschumm751** [comment]
It looks like if you use the workaround for helm / k8s on v.20, the config ui will fail to load with a 404 as it calls the azuredevops plugin which is not loaded.

**Comment by klesh** [comment]
hi, @eschumm751 you are right, and it just got fixed by https://github.com/apache/incubator-devlake/pull/6847, will cherry pick it back to v0.20 asap

**Comment by klesh** [comment]
@eschumm751 it has been cherry-picked, will be included in `v0.20.0-beta8`

**Comment by eschumm751** [comment]
@klesh Thank you!  v 0.20.0 beta8 loads successfully.  I think the underlying issue with running python plugins still persists though:  I get the poetry crash in my k8s cluster if the backend tries to run the scripts in /app/python/plugins.  The cluster doesn't allow running as the root user.  This works fine locally in podman however.

**Comment by klesh** [comment]
@eschumm751 Not a expect on k8s. But why do scripts in /app/python/plugins require root privileges?
@keon94 any idea?

**Comment by ZhangNing10** [comment]
hi @eschumm751 , what is the error message ?

**Comment by eschumm751** [comment]
level=error msg="./run.sh: 20: poetry: Permission denied"

**Comment by matrixji** [comment]
> level=error msg="./run.sh: 20: poetry: Permission denied"

As devlake user in container is with uid=1010, and gid=010.
I think you could try with `runAsUser: 1010`

**Comment by eschumm751** [comment]
I appreciate the suggestion.  Unfortunately the cluster user's security context is restricted to not allow that... Users are in the 1001840000 range...
